version: '3'
services:
  app:
    container_name: nextjs_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - node_modules:/app/node_modules

    tty: true
    ports:
      - 8002:8002
    depends_on:
      - db
    environment:
      - POSTGRES_PRISMA_URL=postgresql://myuser:mysecretpassword@db:5432/mydatabase?schema=public

  db:
    container_name: postgres_db
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data
volumes:
  postgres_db:
  node_modules:
